# Generated by Django 5.0.7 on 2024-08-05 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20210322_2234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
